import "./App.css";

function App() {

  const machine = {
    id: "ENGINE-001",
    temperature: 82,
    vibration: 0.84,
    rpm: 1800,
    load: 72,

    failureProbability: 0.89,
    healthScore: 11,

    decision: "REPLACE",

    explanation: {
      temperature: 0.151875,
      vibration: 0.23625,
      rpm: 0.0075,
      load: 0.134375
    }
  };

  return (
    <div className="app">

      <header className="header">

        <div>
          <h1>MACHINA</h1>
          <p>AI Industrial Maintenance Intelligence</p>
        </div>

        <div className="status">
          <span className="status-dot"></span>
          ENGINE-001 · ONLINE
        </div>

      </header>


      <main className="dashboard">

        {/* Health */}

        <section className="health-section">

          <div className="health-card">

            <p className="label">MACHINE HEALTH</p>

            <div className="health-score">
              {machine.healthScore}
              <span>/100</span>
            </div>

            <div className="health-bar">
              <div
                className="health-fill"
                style={{
                  width: `${machine.healthScore}%`
                }}
              ></div>
            </div>

          </div>


          <div className="risk-card">

            <p className="label">FAILURE RISK</p>

            <div className="risk-value">
              {Math.round(machine.failureProbability * 100)}%
            </div>

            <p>Predicted failure probability</p>

          </div>

        </section>


        {/* Sensors */}

        <section className="panel">

          <h2>Sensor Data</h2>

          <div className="sensor-grid">

            <Sensor
              label="Temperature"
              value={machine.temperature}
              unit="°C"
            />

            <Sensor
              label="Vibration"
              value={machine.vibration}
              unit=""
            />

            <Sensor
              label="RPM"
              value={machine.rpm}
              unit=""
            />

            <Sensor
              label="Load"
              value={machine.load}
              unit="%"
            />

          </div>

        </section>


        {/* SHAP */}

        <section className="panel">

          <h2>Why is the model concerned?</h2>

          <p className="description">
            SHAP feature contributions for the current prediction.
          </p>

          <Explanation
            label="Vibration"
            value={machine.explanation.vibration}
          />

          <Explanation
            label="Temperature"
            value={machine.explanation.temperature}
          />

          <Explanation
            label="Load"
            value={machine.explanation.load}
          />

          <Explanation
            label="RPM"
            value={machine.explanation.rpm}
          />

        </section>


        {/* Decision */}

        <section className="decision-card">

          <p className="label">MAINTENANCE DECISION</p>

          <h2>{machine.decision}</h2>

          <p>
            Decision generated by the Machina Decision Engine.
          </p>

        </section>

      </main>

    </div>
  );
}


function Sensor({ label, value, unit }) {

  return (
    <div className="sensor">

      <p>{label}</p>

      <strong>
        {value} {unit}
      </strong>

    </div>
  );
}


function Explanation({ label, value }) {

  const percentage = Math.min(
    Math.abs(value) * 300,
    100
  );

  return (
    <div className="explanation">

      <div className="explanation-header">

        <span>{label}</span>

        <span>
          +{value.toFixed(3)}
        </span>

      </div>

      <div className="explanation-bar">

        <div
          className="explanation-fill"
          style={{
            width: `${percentage}%`
          }}
        ></div>

      </div>

    </div>
  );
}


export default App;